### ISSUE TITLE
Region-specific live stream is not possible to chose

### ISSUE THREAD

**Issue by Cyber83** [s0faking/plugin.video.orftvthek#22] opened 2016-09-06 17:46 UTC
hello,

orf2 offers at 7:00 pm a region-specific live-stream: tirol, vorarlberg, salzburg, etc.
by whatever reason I cannot chose which stream I want to see, which results in a wrong region I have to watch.

have attached 3 wireshark traces, two of them are done with my mobile phone where i can select the wanted region. have selected "tirol" and "niederösterreich".
the other stream is from kodi, triggered by the only "ORF2 Live" selection.

please tell me if there is a config possibility, i could not find one so far which helped.
please tell me if I can help anyhow.

BR
Alois
[tvthek.zip](https://github.com/s0faking/plugin.video.orftvthek/files/457373/tvthek.zip)

**Comment by s0faking** [comment] 2016-09-07 04:33
Hi Alois,

to be honest, i have never used that feature. I will take a peek on the site structure at 7pm and see what i can do. Did you try it with the ServiceAPI Option on? 

Cheers,
s0fa

**Comment by s0faking** [comment] 2016-09-10 17:11
Hi Alois,

i had a look now and i think the problem is that you haven't selected "Use ServiceAPI" in the TVthek Addon Settings. If you do that you will see a "Stream" selection when entering the "Live" section. The HtmlScraper(Use ServiceAPI disabled) does not scrape that information. I will try to change that when i got some spare

Cheers,
s0fa

**Comment by s0faking** [comment] 2016-10-30 11:08
Hi Alois,

i implemented the feature yesterday. i need to test a little before i push it to the offical repo. i'm currently on vacation, so i will take a look next week. please checkout 0.6.0 if you can't wait ;)

cheers,
s0fa

**Comment by s0faking** [comment] 2016-11-03 14:07
Issue should be fixed now

**Closed by s0faking** 2016-11-03 14:07 UTC
