### ISSUE TITLE
Randomly switching channels

### ISSUE THREAD

**Issue by tschoartschi** [s0faking/plugin.video.orftvthek#18] opened 2016-03-29 13:39 UTC
Hi!

When I use this plugin, sometimes it happens that the channels are randomly switched. In practice this means that when I watch ORF 1 the channel switches to ORF 2 or ORF Sport+, without a user action from my side. I'm not sure how to reproduce this issue and I also don't know how I could provide you details. So let me know how I could help fixing this issue. 

I use this plugin with Raspberry Pi 2 with OSMC.

Thanks

**Comment by s0faking** [comment] 2016-03-29 14:52
hi tschoartschi,

thx for the feedback. can you post a logfile? which osmc version are you using? you are talking about the livestream feature right?

grz

**Comment by tschoartschi** [comment] 2016-03-29 14:59
Yes it only occurred with the livestream feature. How can I access the logfile? Do you have any tutorial? When I'm at home I'll look up the osmc version and let you know asap.

**Comment by tschoartschi** [comment] 2016-03-29 19:02
I'm using OSMC 2016.02-1 (kernel: Linux 4.4.1-1-osmc) running Kodi 16.0

For the log files let me know how I get them

**Comment by s0faking** [comment] 2016-03-29 21:28
thx. you can check this guide for the log thingy: http://kodi.wiki/view/Log_file/Easy

**Comment by tschoartschi** [comment] 2016-04-07 18:56
It is hard to log this issue, because it happens just randomly and is not really reproducible. I'm not sure if the log file helps you. Let me know what you think. I attached the file here: 

[kodi-short.txt](https://github.com/s0faking/plugin.video.orftvthek/files/209012/kodi-short.txt)

**Comment by s0faking** [comment] 2016-04-10 09:58
so far i can see that the stream seems to drop while playing the video. can you rule out your internet connection on this? Can't really find the problem that causes the channel switch. Can you check your "Wiedergabeliste"(playlist) while playing the livestream? Are there multiple items or just the one you are watching? Are you using the "Service API" Scraper or the Generic Scraper(U can check this in the addon settings)?

**Comment by tschoartschi** [comment] 2016-05-03 19:48
I don't think it is a problem with the internet connection since the stream still works but just with a different channel. It is hard to log this issue because it just randomly happens. Today it happened again. See the log, it happened around 20:54. I can not see something special in the log but I don't know what I should look for. 

[kodi.txt](https://github.com/s0faking/plugin.video.orftvthek/files/247618/kodi.txt)

The playlist only shows one entry and I'm not using the Service API.

**Comment by s0faking** [comment] 2016-05-05 12:35
hm according to your attached log kodi never changed the channel. When you look through the lines you can see the HLS Calls when the line starts with 

"[hls,applehttp] HLS request for url 'http://185.85.28.17/orf1/q6a.sdp/"

i think there might be a f***up on the Stream Playlist on the ORF side, meaning that the playlist returns the wrong channel stream and passes it to kodi. But i can't seem to reproduce the issue on my kodi setup. i will try to get a OSMC setup together to test this. 

Can anyone else confirm this issue on OSMC or any other Platform?

**Comment by mablae** [comment] 2016-05-05 13:17
@s0faking OSMC? I can try to help, having OE on Rpi and Native Linux x64 Setups

**Comment by s0faking** [comment] 2016-05-05 13:35
awesome. can you try to reproduce the issue on your RPI (OSMC). I already tried reproducing the whole thing on my x64 linux setup(yaVDR) & Openelec without success.

**Comment by mablae** [comment] 2016-05-05 13:43
@s0faking I am already flashing this OSMC thing.I will report back.

**Comment by mablae** [comment] 2016-05-05 13:45
@s0faking The OSMC installer app is quite nice, btw. SD Card flashing with Wi-Fi setup and so on.

**Comment by s0faking** [comment] 2016-05-30 12:58
@mablae were you able to reproduce the issue

@tschoartschi i tested the whole thing with the newest OSMC and a PI2. Couldn't reproduce the issue though

**Comment by tschoartschi** [comment] 2016-05-30 13:25
@s0faking I'm also not sure how to reproduce it. And if the logs are fine, maybe there is an error with the ORF Videothek? It really happens rarely and so it is not really annoying. If no one can reproduce it in a sane manner, I think you could close this issue with a "can not reproduce"-tag

**Comment by mablae** [comment] 2016-05-31 15:59
@s0faking Sorry, I didn't come to testing it.. The OSMC was stuck booting and then I gave up on that day.

**Comment by s0faking** [comment] 2016-06-03 21:30
@mablae no worries

i'm gonna close this for now. Please feel free to reopen if you can reproduce this

**Closed by s0faking** 2016-06-03 21:30 UTC
